name: Local Config
version: 1.0.0
schema: v1

models:
  - name: Llama 3.2
    provider: ollama
    model: llama3.2:3b
    apiBase: http://localhost:11434

  - name: Qwen2.5 Coder
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://localhost:11434

  - name: Stable Code
    provider: ollama
    model: stable-code:3b
    apiBase: http://localhost:11434

  - name: Phi-3 Mini
    provider: ollama
    model: phi3:mini
    apiBase: http://localhost:11434

context: []

mcpServers: []