worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream customer_service {
        server customer_web:5001;
    }

    upstream admin_service {
        server admin_web:5002;
    }

    upstream delivery_service {
        server delivery_web:5003;
    }

    server {
        listen 80;

        location /admin {
            proxy_pass         http://admin_service;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /delivery {
            proxy_pass         http://delivery_service;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Any other traffic goes to Customer Service
        location / {
            proxy_pass         http://customer_service;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # WebSocket support for Socket.IO
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
